### ISSUE TITLE
能量机关预测的程序入口在哪里啊？

### ISSUE THREAD

**Issue by WuyinNian** [XianMengxi/AutoAim_HUST#1]
我想请问一下能量机关预测的程序入口在哪里啊？🤦‍♂️

**Comment by XianMengxi** [comment]
识别线程里，即[AutoAim_HUST](https://github.com/XianMengxi/AutoAim_HUST)/[src](https://github.com/XianMengxi/AutoAim_HUST/tree/main/src)/[armor_detector](https://github.com/XianMengxi/AutoAim_HUST/tree/main/src/armor_detector)/src/detector.cpp

**Comment by WuyinNian** [comment]
好的，谢谢！（solute
